import 'package:realm/realm.dart';

part 'task_model.realm.dart'; // This will be generated by Realm

@RealmModel()
class _Task {
  late String title;
  late String definition;
  late String status;
  DateTime? startTime;
  DateTime? endTime;
  int? duration; // in minutes
}
